# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Francis Oliver Avanceña
email: foavancena@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello! I am Francis and a Management Information Systems professional that currently works in the FinTech Industry in the Philippines.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://francisoliver.dev" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/img/avatar.png
twitter_username: sicnarf_revilo
github_username:  tripeersyou
devto_username: sicnarf_revilo
twitter:
  username: sicnarf_revilo
  card: summary
social:
  name: Francis Oliver Avanceña
  links:
    - https://facebook.com/sicnarfzurcrevilo
    - https://twitter.com/sicnarf_revilo
    - https://github.com/tripeersyou
    - https://linkedin.com/in/francisavancena
    - https://dev.to/sicnarf_revilo
    - https://instagram.com/francis.avancena
# Build settings
pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  title: ":title - Page :num"
markdown: kramdown
permalink: "/blog/:title"
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
    
include:
  - _redirects
  - search.xml

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
